version: '3'
services:
  php_apcahce_node:
    networks:
      - backend
    image: thecodingmachine/php:7.1-v1-apache-node8
    volumes:
      - ./src:/var/www/html:delegated
#      - ./docker/php/auth.json:/home/docker/.composer/auth.json
      - ./docker/apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    environment:
#      Compiled in PHP (cannot be disabled): mbstring ftp mysqlnd
#      Enabled by default: apcu mysqli opcache pdo pdo_mysql redis zip soap
#      Available extenstions:
#      amqp ast bcmath blackfire bz2 calendar dba enchant ev event exif gd gettext gmp igbinary imap intl ldap mcrypt
#      memcached mongodb pcntl pdo_dblib pdo_pgsql pgsql pspell shmop snmp sockets sysvmsg sysvsem sysvshm tidy wddx
#      weakref(-beta) xdebug xmlrpc xsl yaml
      PHP_EXTENSION_XDEBUG: 1
#      PHP_EXTENSION_BLACKFIRE: 1
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_IMAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_MCRYPT: 1
#      memcached fails with php7.2
      PHP_EXTENSION_MEMCACHED: 1
      PHP_EXTENSION_MONGODB: 1
      PHP_EXTENSION_PCNTL: 1
#      tidy fails with php7.2
      PHP_EXTENSION_TIDY: 1
      PHP_EXTENSION_XSL: 1
      PHP_INI_ERROR_REPORTING: E_ALL
  memcached:
    image: memcached:alpine
    networks:
      - backend
  redis:
    image: redis:alpine
    networks:
      - backend
  db:
    networks:
      - backend
    image: mysql:5.7
    volumes:
      - './docker/mysql/db:/var/lib/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
  phpmyadmin:
    # restart: always
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    ports:
      - '8080:80'
    environment:
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db
networks:
  backend: null
