version: '3'
services:
  php_apcahce_node:
    networks:
      - backend
    image: thecodingmachine/php:7.2-v1-apache-node8
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/php/auth.json:/home/docker/.composer/auth.json
    ports:
      - "80:80"
    environment:
      PHP_EXTENSION_XDEBUG: 1
  memcached:
    image: memcached:alpine
    networks:
      - backend
  redis:
    image: redis:alpine
    networks:
      - backend
  db:
    networks:
      - backend
    image: mysql:5.7
    volumes:
      - './docker/mysql/db:/var/lib/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
  phpmyadmin:
    # restart: always
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    ports:
      - '8080:80'
    environment:
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db
networks:
  backend: null
